#!/bin/sh

output_config() {
    echo "graph_title Munin master error-rate"
    echo "munin_master_errors.label Errors per second"
    echo "munin_master_errors.type DERIVE"
    echo "graph_category munin"
}

output_values() {
    printf "munin_master_errors.value %d\n" $(number_of_errors)
}

number_of_errors() {
    egrep -c "\[ERROR\]|\[FATAL\]" /var/log/munin/munin-update.log
}

output_usage() {
    printf >&2 "%s - plugin to monitor error-rate in munin log\n" ${0##*/}
    printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
    0)
        output_values
        ;;
    1)
        case $1 in
            config)
                output_config
                ;;
            *)
                output_usage
                exit 1
                ;;
        esac
        ;;
    *)
        output_usage
        exit 1
        ;;
esac
