CREATE TABLE IF NOT EXISTS default.logs
(
    `CODE_FILE` String,
    `CODE_FUNC` String,
    `CODE_LINE` String,
    `INVOCATION_ID` String,
    `LOGGER` String,
    `MESSAGE_ID` String,
    `MESSAGE` String,
    `PRIORITY` String,
    `PROCESS_NAME` String,
    `SYSLOG_FACILITY` String,
    `SYSLOG_IDENTIFIER` String,
    `SYSLOG_PID` String,
    `SYSLOG_TIMESTAMP` String,
    `THREAD_NAME` String,
    `TID` String,
    `UNIT` String,
    `_AUDIT_LOGINUID` String,
    `_AUDIT_SESSION` String,
    `_BOOT_ID` String,
    `_CAP_EFFECTIVE` String,
    `_CMDLINE` String,
    `_COMM` String,
    `_EXE` String,
    `_GID` String,
    `_HOSTNAME` String,
    `_KERNEL_DEVICE` String,
    `_KERNEL_SUBSYSTEM` String,
    `_MACHINE_ID` String,
    `_PID` String,
    `_SELINUX_CONTEXT` String,
    `_SOURCE_MONOTONIC_TIMESTAMP` String,
    `_SOURCE_REALTIME_TIMESTAMP` String,
    `_STREAM_ID` String,
    `_SYSTEMD_CGROUP` String,
    `_SYSTEMD_INVOCATION_ID` String,
    `_SYSTEMD_SLICE` String,
    `_SYSTEMD_UNIT` String,
    `_TRANSPORT` String,
    `_UDEV_SYSNAME` String,
    `_UID` String,
    `__CURSOR` String,
    `__MONOTONIC_TIMESTAMP` String,
    `__REALTIME_TIMESTAMP` String
)
ENGINE = MergeTree
ORDER BY __MONOTONIC_TIMESTAMP
SETTINGS index_granularity = 8192
