#!/usr/bin/env python3
#
# jupycron
#
# Warning: malicious jupyter filenames might allow command injection
#
# jupycron itself runs as root but the notebooks are run as jupyter
# monitor with: sudo journalctl -f -u jupycron

from datetime import datetime
from pathlib import Path
import pathlib
import hashlib
import json
import logging
import subprocess
import time

import jinja2  # debdeps: python3-jinja2

DEFAULT_NOTEBOOK_PATH = Path("/var/lib/jupyter/notebooks/")
DEFAULT_OUTPUT_PATH = Path("/var/lib/jupyter/notebooks/jupycron")
RUNTIME_LIMIT = 3600
MAXMEM = 1000
log = logging.getLogger("jupycron")
log.setLevel(logging.DEBUG)

try:
    from systemd.journal import JournalHandler

    log.addHandler(JournalHandler())
except ImportError:
    log.addHandler(logging.StreamHandler())


def load_history() -> None:
    fn = DEFAULT_OUTPUT_PATH / ".history.json"
    try:
        with fn.open() as f:
            j = json.load(f)
    except Exception:
        j = {}
    return j


def save_history(j: dict) -> None:
    fn = DEFAULT_OUTPUT_PATH / ".history.json"
    with fn.open("w") as f:
        json.dump(j, f)
    log.debug(f"{fn} written")


def extract_jupycron_conf(nb: Path):
    assert nb.is_file()
    # Hacky but fast extractor
    read_data = 0
    for line in nb.open("rb"):
        #       example:
        #       "# jupycron: {\"every\": \"60 min\"}\n",
        idx = line.find(b'"# jupycron:')
        if idx >= 0:
            try:
                line = line[idx:].strip()
                lb = line.find(b"{")
                rb = line.rfind(b"}")
                line = line[lb : rb + 1]
                line = line.decode("unicode_escape")
                return json.loads(line)
            except Exception:
                pass

        read_data += len(line)
        if read_data > 500_000:
            return None

    # cmd = ["jupyter-nbconvert", "--to", "python", "--stdout", nb.as_posix()]
    # py = subprocess.check_output(cmd, timeout=5)
    # out = py.decode().splitlines()
    # for li in out:
    #     if not li.startswith("# jupycron"):
    #         continue
    #     _1, _2, conf = li.split(None, 2)
    #     return json.loads(conf)


time_lookup = {"min": 60, "hour": 3600, "day": 86400, "week": 604800, "month": 2628000}


def time_to_run(conf):
    try:
        num, dimension = conf.get("every", "").split()
        dimension = dimension.rstrip("s")
        seconds = int(float(num) * time_lookup[dimension])
    except Exception:
        # todo: log
        return False
    return int(time.time()) % seconds == 0


def generate_unit_name(nb):
    hash_ = nb.as_posix().encode()
    hash_ = hashlib.sha224(hash_).hexdigest()[:10]
    return nb.stem.replace(" ", "_") + "-" + hash_


def run_notebook(nb, conf):
    elapsed = 0.0
    htmlfn = nb.with_suffix(".html").as_posix()
    htmlfn = htmlfn.replace(
        DEFAULT_NOTEBOOK_PATH.as_posix(), DEFAULT_OUTPUT_PATH.as_posix()
    )
    unitname = generate_unit_name(nb)
    # maxruntimesec = min(conf.get("MaxRuntime", RUNTIME_LIMIT), RUNTIME_LIMIT)
    memorymax = min(conf.get("MaxMem", MAXMEM), MAXMEM)
    cmd = [
        "systemd-run",
        f"--unit={unitname}",
        "--collect",
        "--wait",
        # "--uid=jupyter",
        "--gid=jupyter",
        "--working-directory=/var/lib/jupyter/notebooks/",
        # "--scope",
        "-p",
        f"MemoryMax={memorymax}M",
        # "-p",
        # f"MaxRuntimeSec={maxruntimesec}",
        "--setenv=AUTORUN=1",
        "jupyter-nbconvert",
        "--execute",
        "--to",
        "html",
        "--allow-errors",
        f"--output={htmlfn}",
        nb.as_posix(),
    ]
    log.info(f"running {' '.join(cmd)}")
    try:
        t0 = time.perf_counter()
        p = subprocess.check_output(cmd, stderr=subprocess.PIPE, timeout=5)
        elapsed = time.perf_counter() - t0
        out = p.decode()
        log.info(f"{unitname} output:\n{out}")
        res = "success"
    except subprocess.CalledProcessError as e:
        log.info(f"Error in {unitname}. Output:\n{e.output.decode()}")
        res = "failed"

    log.info(f"{unitname} done")
    return (res, elapsed)


def list_ipynb_files() -> list:
    out = []
    for nb in DEFAULT_NOTEBOOK_PATH.glob("**/*autorun*.ipynb"):
        # Skip hidden files
        if any(p.startswith(".") for p in nb.parts):
            continue
        out.append(nb)

    return out


def update_history(run_history, history):
    nbs = history.get("notebooks", {})
    for nb in tuple(nbs.keys()):
        if nb not in run_history:
            log.debug(f"Discarding deleted notebook {nb}")
            nbs.pop(nb)

    for nb, data in run_history.items():
        nbs[nb] = data

    history["notebooks"] = nbs


def generate_summary(history: dict):
    env = jinja2.Environment()
    tpl = env.from_string(
        """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Jupycron summary</title>
  <style>
    table {
        margin: 2em;
        padding: 1em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border-spacing: 10px;
    }

  </style>
</head>

<body>
  <table>
    <tr>
        <th>Status</th>
        <th>Last run time</th>
        <th>Name</th>
        <th>Run duration</th>
    </tr>
    {% for nb, (tstamp, res, elapsed) in notebooks.items() %}
    <tr>
      {% if res == 'success': %}
      <td>🟢</td>
      {% elif res == 'failed': %}
      <td>🔴</td>
      {% else %}
      <td>🛇</td>
      {% endif %}
      <td>{{ tstamp }}</td>
      <td><a href=/notebooks/notebooks/{{ nb }}>{{ nb }}</a>
      </td>
      <td>{{ elapsed|round(2) }}</td>
    </tr>
    {% endfor %}
  </table>
</body>
</html>
"""
    )
    html = tpl.render(notebooks=history["notebooks"])

    fn = DEFAULT_OUTPUT_PATH / "summary.html"
    fn.write_text(html)
    log.debug(f"{fn} written")


def main():
    history = load_history()
    notebooks = list_ipynb_files()
    log.debug(f"Found {len(notebooks)} notebooks")
    run_history = {}
    for nb in notebooks:
        nb_rel = nb.relative_to(DEFAULT_NOTEBOOK_PATH)
        try:
            conf = extract_jupycron_conf(nb)
            if conf is None:
                log.debug(f"Skpping {nb}")
                run_history[nb_rel.as_posix()] = ("", "not run", 0)
                continue

            if time_to_run(conf):
                tstamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
                res, elapsed = run_notebook(nb, conf)
                run_history[nb_rel.as_posix()] = (tstamp, res, elapsed)

        except Exception as e:
            log.error(e)

    update_history(run_history, history)
    save_history(history)
    generate_summary(history)


if __name__ == "__main__":
    main()
