---

# Deploy PostgreSQL 11.7

- import_playbook: ansible-version.yml

- hosts: ams-pg.ooni.org
  gather_facts: true # to gather `ansible_service_mgr`
  tags: postgresql11
  roles:
    - role: postgresql11

- hosts: ams-pg-test.ooni.org
  gather_facts: true # to gather `ansible_service_mgr`
  tags: postgresql11
  roles:
    - role: postgresql11

#- name: install prometheus-postgres-exporter
#  apt:
#    cache_valid_time: 86400
#    install_recommends: no
#    name: prometheus-postgres-exporter
#
#
#- name: install prom process exporter
#  apt:
#    cache_valid_time: 86400
#    install_recommends: no
#    name: prometheus-process-exporter
#
#- name: install prom Nginx exporter
#  apt:
#    cache_valid_time: 86400
#    install_recommends: no
#    name: prometheus-nginx-exporter
#
#
#- name: install prox Haproxy exporter
#  apt:
#    cache_valid_time: 86400
#    install_recommends: no
#    name: prometheus-haproxy-exporter
#
