- hosts: registry.proteus.test.ooni.io
  roles:
    - role: letsencrypt
      letsencrypt_domains: ["registry.proteus.test.ooni.io"]
      letsencrypt_nginx: yes
    - role: ooni-registry
      letsencrypt_domains: ["registry.proteus.test.ooni.io"]
      orchestra_registry_https_port: 443
      orchestra_database_url: "{{ orchestra_database_url_testing }}"
      orchestra_auth_jwt_secret : "{{ orchestra_auth_jwt_secret_testing }}"
      orchestra_auth_admin_password : "{{ orchestra_admin_password_testing }}"

- hosts: registry.proteus.ooni.io
  roles:
    - role: letsencrypt
      letsencrypt_domains: ["registry.proteus.ooni.io"]
      letsencrypt_nginx: yes
    - role: ooni-registry
      letsencrypt_domains: ["registry.proteus.ooni.io"]
      orchestra_registry_https_port: 443
      orchestra_auth_admin_password : "{{ orchestra_admin_password }}"
