---
#
## roles/ooca-cert/tasks/main.yml
#
## The host keys and certs are ephemeral and allow cert rotation (without downtimes).
## The pusher_ca is used as general CA for simplicity.
#
- name: Create ssl key directory
  file: path={{ ooca_ssl_dir }} state=directory owner=root group={{ ooca_group }} mode=0710

- name: Generate certificates locally
  tags: deploy-prom-exp-certs
  # runs locally. Generates: ooca-node.cert ooca-node.req ooca-node.key ooca-node.chain oonicacert.pem
  delegate_to: 127.0.0.1
  shell: |
    # Extract CA PEM cert
    ./vault view files/pusher_ca.key.vault | openssl req -x509 \
        -new -nodes -key /dev/stdin -sha256 -days 3650 \
        -addext "subjectAltName = DNS:*.ooni.org" \
        -subj '/O=OONI/OU=CA/CN=ooni.org' -out oonicacert.pem
    # Generate new host privkey and PEM cert request
    openssl req -newkey rsa:2048 -nodes -days 3650 -keyout ooca-node.key \
        -addext "subjectAltName = DNS:*.ooni.org" \
        -out ooca-node.req -subj '/CN=ooni.org/O=OONI temp CA/C=US' -batch
    # Generate ooca-node PEM cert
    ./vault view files/pusher_ca.key.vault | openssl x509 -req -days 3650 \
        -set_serial 01 -in ooca-node.req -out ooca-node.cert -CA oonicacert.pem \
        -CAkey /dev/stdin
    # Chain certs
    cat oonicacert.pem ooca-node.cert > ooca-node.chain
