#!/bin/bash
gitroot=$(git rev-parse --show-toplevel)
export TRAVIS_VAULT_SECRET=$("$gitroot/ansible/vault" view "$gitroot/ansible/.travis.vaultpw")
set -o xtrace
set -o errexit
cd "$gitroot/ansible"
for vault in $(find . -type f -name vault ! -perm /111); do
    ./vault view "$vault" \
        | python -c 'import sys, os, yaml; yaml.safe_dump({k: "TRAVIS_" + os.urandom(8).encode("hex") for k in yaml.load(sys.stdin).keys()}, sys.stdout, default_flow_style=False)' \
        | ansible-vault --vault-password-file ./.travis.password-pipe encrypt --output "${vault%/vault}/.travis.vault"
done
