#!/bin/bash
gitroot=$(git rev-parse --show-toplevel)
export TRAVIS_VAULT_SECRET=$("$gitroot/ansible/vault" view "$gitroot/ansible/.travis.vaultpw")

uname=`uname -s`
if [ "$uname" = Linux ]; then
  perm_any=/ # -perm +mode is no longer supported.  Use -perm /mode instead. (c) man find
else
  perm_any=+
fi

set -o xtrace
set -o errexit
cd "$gitroot/ansible"
# to re-make only modified files
make -j1 -f /dev/stdin $(find . -type f -name vault ! -perm ${perm_any}111 | sed s,/vault$,/.travis.vault,) <<'EOF'
%/.travis.vault : %/vault
	./vault view "$^" | ../scripts/mk-travis-vault-single "$^" | ansible-vault --vault-password-file ./.travis.password-pipe encrypt --output "$@"
EOF
