#!/bin/bash
#
# That's the script to update group_vars/all/vault with new root password
# digest and mail it to openobservatory.org "admins".
#

set -o errexit

adm_mails="vasilis arturo leonid simone" # email accounts of people listed in adm_logins

gitroot=$(git rev-parse --show-toplevel)

now=$(TZ=UTC date +%Y%m%d%H%M)
fname="ooni-sysadmin-${now}.rootpw.gpg"
pw=$(./dicepass)
digest=$(echo "$pw" | mkpasswd --method=sha-512 --stdin)

cd "$gitroot/ansible"
EDITOR="sed -i 's,^vault_root_password_digest:.*,vault_root_password_digest: \"${digest}\",; s,^vault_root_password_mtime:.*,vault_root_password_mtime: ${now},'" ./vault edit group_vars/all/vault

uid=$(id -u)
# goto tmpfs
cd /run/user/"${uid}"


for u in $adm_mails; do
    intro=$(head -c 42 /dev/urandom | base64)
    outro=$(head -c 42 /dev/urandom | base64)
    gpg --encrypt -r "${u}@openobservatory.org" >"$fname" <<EOF
==> ${intro} <==

OONI Root ${now} password: $pw

Consider re-generating the password if it's ever used for VNC.

==> ${outro} <==
EOF
    mutt.tor -s 'OONI Root password' -a "$fname" -- "${u}@openobservatory.org" <<EOF
Hello, ${u}@ooni.

That's some entropy for you (and your fellows: $adm_mails).

Keep secrets secret!
EOF
    shred --remove "$fname"
done
