- name: install apt requirements
  apt:
    cache_valid_time: 86400
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - dirmngr

- name: create clickhouse gpg keyring
  shell:
    cmd: "wget -qO- 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3a9ea1193a97b548be1457d48919f6bd2b48d754' | gpg --dearmor | tee /usr/share/keyrings/clickhouse-keyring.gpg"
    creates: "/usr/share/keyrings/clickhouse-keyring.gpg"
    warn: false

- name: set clickhouse repos
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main"
    state: present
    update_cache: true

- name: install clickhouse
  apt:
    cache_valid_time: 0
    name:
      - clickhouse-server={{ clickhouse_pkg_ver }}
      - clickhouse-client={{ clickhouse_pkg_ver }}
  vars:
    clickhouse_pkg_ver: 23.2.*


- name: mkdir for clickhouse custom config
  file:
    path: "/etc/clickhouse-server/config.d/"
    state: directory
    owner: clickhouse
    group: clickhouse
    mode: 0744

- name: install clickhouse conf override
  tags: clickhouse
  template:
    src: clickhouse_config.xml
    dest: /etc/clickhouse-server/config.d/ooni_conf.xml
    owner: clickhouse
    group: clickhouse
    mode: 0644
  notify: restart clickhouse


- name: install packages with conda
  shell: "{{ conda_bin }}/conda install -c conda-forge pandas numpy altair clickhouse-driver dask scipy scikit-learn catboost pycountry ujson orjson tqdm seaborn requests maxminddb matplotlib lz4 shap msgpack-python beautifulsoup4"

- name: create yarn gpg keyring
  shell:
    cmd: "wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarn-keyring.gpg"
    creates: "/usr/share/keyrings/yarn-keyring.gpg"
    warn: false

- name: set yarn repos
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/yarn-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main"
- name: install yarn
  apt:
    cache_valid_time: 0
    name:
      - yarn

# Apache Superset setup
- name: install apt requirements for superset
  apt:
    state: present
    name:
      - build-essential
      - python-dev
      - libssl-dev 
      - libffi-dev
      - libsasl2-dev 
      - libldap2-dev
      - default-libmysqlclient-dev

- name: install superset with pip
  shell: "{{ conda_bin }}/pip install apache-superset

- name: initialize superset DB
  shell: "{{ conda_bin }}/superset db upgrade

