---
- import_playbook: ansible-version.yml

- hosts: ams-api.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "ams-api.ooni.nu"
        - "api.ooni.io"
    - role: ooni-measurements
      tags: "api"
      ssl_domain: ams-api.ooni.nu
