FROM debian:jessie
RUN apt-get -y update
RUN apt-get install -y git-core ansible
RUN git clone {{ ooni_sysadmin_repo }} /tmp/ooni-sysadmin
WORKDIR /tmp/ooni-sysadmin/
RUN ansible-playbook -i "local," -v ansible/install-oonibackend.yml -c local
CMD ["/usr/local/bin/oonib", "-c", "{{ oonibackend_conf }}"]
