FROM debian:jessie
RUN gpg --keyserver pool.sks-keyservers.net --recv A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
RUN gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
RUN echo "deb http://deb.torproject.org/torproject.org jessie main" \
         | tee /etc/apt/sources.list.d/tor.list
RUN apt-get -y update
RUN apt-get install -y git-core python-pip python-dev libsqlite3-dev \
                       libffi-dev tor deb.torproject.org-keyring
{% if ( oonibackend_git_install|default('true')|bool ) %}
RUN pip install git+{{ ooni_backend_repo }}@{{ooni_backend_git_hash }}
{% else %}
RUN pip install oonibackend
{% endif %}
CMD ["/usr/local/bin/oonib", "-c", "{{ oonibackend_conf }}"]
